collections:
  authors:
  events:
    icon: event
    output: true
  bicyclerides:
    output: true
    icon: bicycle
  petitions:
    output: true
    icon: petition
  publiccomments:
    output: true
    icon: speech
  writtencomments:
    output: true
    icon: written_comment
  series:
    output: true
  photogalleries:
    output: true
  podcastepisodes:
    output: true
  instagramposts:
    output: true
  instagramreels:
    output: true
  links:
    output: false
  youtube:
    output: true
  specialdays:
    output: true
  updates:
    output: false

  # Collections added as part of STLC update
  groups:
    layout: stlc-default
    output: true
    order:
      - dallas-neighbors-for-housing.md
      - dallas-bicycle-coalition.md
      - data-dallas-area-transit-alliance.md
      - dallas-housing-coalition.md
      - dfw-urbanistas.md
      - better-block.md
      - congress-new-urbanism-north-texas.md
      - gdpc-greater-dallas-planning-council.md
      - sunrise-movement-dallas.md

media_library:
  name: uploadcare
  config:
    publicKey: d50f0c9e161743596858

url: https://dallasurbanists.com

plugins:
  - jekyll-dotenv