collections:
  # Collections added as part of STLC update
  groups:
    layout: stlc-default
    output: true
    order:
      - dallas-neighbors-for-housing.md
      - dallas-bicycle-coalition.md
      - data-dallas-area-transit-alliance.md
      - dallas-housing-coalition.md
      - dfw-urbanistas.md
      - better-block.md
      - congress-new-urbanism-north-texas.md
      - gdpc-greater-dallas-planning-council.md
      - sunrise-movement-dallas.md

  # Collections added for mixer and hyperlocal pages
  mixers:
  hyperlocals:
    output: true

media_library:
  name: uploadcare
  config:
    publicKey: d50f0c9e161743596858

url: https://dallasurbanists.com

plugins:
  - jekyll-dotenv