---
# this frontmatter section tells Jekyll to process this file, allowing us to use variables like site.tags
---
backend:
  name: git-gateway
  branch: main
  repo: DallasUrbanists/dallasurbanists.com

site_url: https://dallasurbanists.com
logo_url: https://dallasurbanists.com/assets/dallas-urbanists-wordmark.svg
publish_mode: editorial_workflow
media_folder: "assets/cover_images"
search: false

collections:

  - name: "events"
    label: "Events"
    label_singular: "Event"
    folder: "_events"
    create: true
    editor: { preview: false }
    {% raw %}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    {% endraw %} # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Start Date", name: "start_date", widget: "datetime"}
      - {label: "End Date", name: "end_date", widget: "datetime", required: false}
      - {
          label: 'Host',
          name: 'host',
          widget: 'relation',
          collection: 'groups',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
        }
      - {label: "Webpage", name: "webpage", widget: "string", required: false}
      - {label: "Featured?", name: "is_featured", widget: "boolean", required: false}
      - label: "Location"
        name: "location"
        widget: "object"
        summary: "{{ fields.name }}"
        hint: "Leave this alone if your event is online only."
        fields:
          - {label: "Name of Venue/Building/Business", name: "name", widget: "string", hint: "e.g., Bryan Street Tavern", required: false}
          - {label: "Street Address", name: "address", widget: "string", hint: "e.g., 4315 Bryan St", required: false}
          - {label: "City", name: "city", widget: "string", default: "Dallas" }
          - {label: "Zip", name: "zip", widget: "number", required: false, hint: "e.g., 75204"}
      - {label: "Details", name: "body", widget: "markdown"}

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "blog/_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    {% raw %}
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    {% endraw %} # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          display_fields: [display_name],
          search_fields: [display_name],
          value_field: 'name',
        }
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Cover Image", name: "cover_image", widget: "image", required: false}
      - {
          label: "Tags", 
          name: "tags", 
          widget: "select", 
          required: false, 
          multiple: true, 
          
          {%- capture options -%}
          {%- for tag in site.tags -%}
          "{{tag[0]}}",
          {%- endfor -%}
          
          {%- for tag in site.data.tags.items -%}
          "{{tag.name}}",
          {%- endfor -%}
          {%- endcapture -%}
          {% assign sorted_options = options | split: "," | uniq | sort | join: ", " %}
          
          options: [{{ sorted_options }}] 
        }  

  - name: "authors"
    label: "Authors"
    label_singular: "Author"
    folder: "_authors/"
    {% raw %}
    slug: "{{name}}"
    {% endraw %}
    output: true
    create: true
    editor: { preview: false }
    fields:
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Email', name: 'email', widget: 'string' }
      - { label: 'Twitter Handle', name: 'twitter', widget: 'string', required: false  }
      - { label: 'Instagram Handle', name: 'instagram', widget: 'string', required: false  }
      - { label: 'Reddit Handle', name: 'reddit', widget: 'string', required: false  }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: "Photo", name: "photo", widget: "image", required: false }

  - name: "groups"
    label: "Groups"
    label_singular: "Group"
    folder: "_groups/"
    {% raw %}
    slug: "{{name}}"
    {% endraw %}
    output: true
    create: true
    editor: { preview: false }
    fields:
      - { label: 'Slug', name: 'name', widget: 'string', hint: 'This is used as a unique URL-safe identifier. May only contain lowercase letters, numbers, and dashes (-). For example: "dallas-neighbors-for-housing"' }
      - { label: 'Name', name: 'display_name', widget: 'string', hint: 'This is the name displayed in the majority of cases. If abbreviation is commonly used, this should start with the full name and end with the abbreviation in parenthesis. For example, "Dallas Area Rapid Tranist (DART)"'}
      - { label: 'Alias', name: 'alias', widget: 'string', hint: 'This is the shorthand name. Put just the abbreviation if commonly used (for example, "DART").', required: false }
      - { label: 'Summary', name: 'summary', widget: 'text', required: false, pattern: ['^.{0,500}$', 'Maximum 500 characters.'], hint: 'This is what people see when they are browsing groups in a catalog, so it should be written like an elevator pitch that quickly explains why someone should join and what differentiates the group from others.'}
      - { label: 'Logo', name: 'logo', widget: 'image' }
      - { label: 'Cover Photo', name: 'cover_photo', widget: 'image' }
      - { label: 'Featured?', name: 'is_featured', widget: 'boolean' }
      - { label: 'Focus Issues', name: 'focus_issues', widget: 'string', required: false }
      - { label: 'Focus Area', name: 'focus_area', widget: 'string', required: false }
      - { label: 'Founded On', name: 'founded_on', widget: 'string', required: false }
      - { label: 'Website', name: 'website', widget: 'string' }
      - label: 'Links'
        label_singular: 'Link'
        summary: '{{ fields.label }}'
        name: 'links'
        widget: 'list'
        allow_add: true
        fields:
          - { label: 'Label', name: 'label', widget: 'string' }
          - { label: 'URL', name: 'url', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'config'
    label: 'Config'
    editor: { preview: false }
    files:
      - label: 'Tag'
        name: 'tag'
        file: '_data/tags.yml'
        fields:
          - label: 'Tags'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }

media_library:
  name: uploadcare
  config:
    publicKey: d50f0c9e161743596858