name: Daily build
on:

  # Allow workflow to be manually run in GitHub
  # @see https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch:

  schedule:
    - cron: '0 7 * * *' # every day at 7:00 AM UTC / 1:00 AM CST
    - cron: '33 8 * * *' # for test, set to run at 3:20 AM CDT / 8:20 AM UTC 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger our build webhook on Netlify
      run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"
      env:
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
