# Build & deploy every day at midnight
# @see https://www.voorhoede.nl/en/blog/scheduling-netlify-deploys-with-github-actions/#github-actions
name: Daily build
on:

  # Allow workflow to be manually run in GitHub
  # @see https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch:

  # Daily at 1:00 AM CST / 7:00 AM UTC
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Build hooks are URLs you can use to trigger new builds and deploys.
    # @see https://docs.netlify.com/configure-builds/build-hooks/?_gl=1%2a1nz54mj%2a_gcl_au%2aNzkwODg3MzAxLjE3MTAxNTg5Njk.
    - name: Trigger our build webhook on Netlify
      run: curl -s -X POST "https://api.netlify.com/build_hooks/${TOKEN}"

      # GitHub repo > Settings > Secrets and variables > Actions > Repository secrets
      env:
        TOKEN: ${{ secrets.NETLIFY_CRON_BUILD_HOOK }}
